# Generated by Django 4.1.5 on 2023-05-23 10:56

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
